# Generated by Django 3.2.4 on 2022-09-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encounter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='pid',
            field=models.BigIntegerField(),
        ),
    ]
