# Generated by Django 3.2.4 on 2022-09-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encounter', '0002_alter_encounter_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='encid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
