# Generated by Django 3.2.4 on 2022-09-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Encounter', '0006_auto_20220925_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicalnotes',
            old_name='facility',
            new_name='type',
        ),
    ]
