# Generated by Django 3.2.4 on 2022-09-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encounter', '0007_rename_facility_clinicalnotes_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProblems',
            fields=[
                ('problemid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pid', models.BigIntegerField()),
                ('problem', models.CharField(blank=True, max_length=30, null=True)),
                ('other', models.CharField(blank=True, max_length=30, null=True)),
                ('coding', models.CharField(blank=True, max_length=50, null=True)),
                ('begindate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('clstype', models.CharField(blank=True, max_length=30, null=True)),
                ('occurence', models.CharField(blank=True, max_length=30, null=True)),
                ('verificationstatus', models.CharField(blank=True, max_length=30, null=True)),
                ('referredby', models.CharField(blank=True, max_length=30, null=True)),
                ('comments', models.TextField(blank=True, max_length=200, null=True)),
                ('outcome', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('pid', models.BigIntegerField()),
                ('prescid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=30, null=True)),
                ('drug', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
