# Generated by Django 3.2.4 on 2022-10-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encounter', '0009_auto_20220929_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctorID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('doj', models.DateField(blank=True, null=True)),
                ('registrationID', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
