# Generated by Django 3.2.4 on 2022-10-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Encounter', '0011_guardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='guardiansex',
        ),
    ]
